version: '3'
services:
  prometheus:
    image: 266822543819.dkr.ecr.us-east-1.amazonaws.com/unholsters:prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/:/etc/prometheus
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

volumes:
  prometheus-data:
