version: '3.3'
services:
  database:
    image: postgres:latest
    environment:
      PGDATA: /pgdata
      POSTGRES_USER: ppagos
      POSTGRES_PASSWORD: ppagos_pass
      POSTGRES_DB: ppagos
    ports:
      - 5432:5432
    volumes:
      - /tmp/database:/var/lib/postgresql/data


