version: '2'
services:
  database:
    image: boris/mariadb
    volumes:
      - "./.data/database:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: 123123

  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    links:
      - database
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_PASSWORD: 123123
