version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - /tmp/prom:/etc/prometheus
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

volumes:
  prometheus-data:
